linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    # - copyloopvar
    - goconst
    - gofmt
    - goimports
    # - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - staticcheck
    # - structcheck // to be fixed by golangci-lint
    - stylecheck
    - typecheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-same-issues: 50
  exclude-dirs:
    - pkg/
    - operatorsync/
    - crypto/bls
    - crypto/secp256k1
    - test/
    - rpc/test/
    - privval

linters-settings:
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 200
  dogsled:
    max-blank-identifiers: 3
  # golint:
  #   min-confidence: 0
  goconst:
    ignore-tests: true
  # maligned:
  #   suggest-new: true
  misspell:
    locale: US
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/rs/zerolog
          - github.com/cometbft/cometbft-db
          - github.com/0xPellNetwork/pelldvs-libs
          - github.com/cosmos
          - github.com/btcsuite/btcd/btcec/v2
          - github.com/BurntSushi/toml
          - github.com/go-git/go-git/v5
          - github.com/go-kit
          - github.com/go-logfmt/logfmt
          - github.com/gofrs/uuid
          - github.com/google
          - github.com/gorilla/websocket
          - github.com/informalsystems/tm-load-test/pkg/loadtest
          - github.com/hashicorp/golang-lru/v2
          - github.com/lib/pq
          - github.com/libp2p/go-buffer-pool
          - github.com/Masterminds/semver/v3
          - github.com/minio/highwayhash
          - github.com/oasisprotocol/curve25519-voi
          - github.com/golang/protobuf/proto
          - github.com/pkg/errors
          - github.com/prometheus
          - github.com/rcrowley/go-metrics
          - github.com/rs/cors
          - github.com/snikch/goodman
          - github.com/spf13
          - github.com/stretchr/testify/require
          - github.com/syndtr/goleveldb
          - github.com/decred/dcrd/dcrec/secp256k1/v4
          - github.com/consensys/gnark-crypto
          - github.com/ethereum/go-ethereum
          - github.com/0xPellNetwork/contracts
          - github.com/naoina/toml
          - github.com/ethereum/go-ethereum/crypto
          - github.com/ethereum/go-ethereum/common
          - github.com/ethereum/go-ethereum/ethclient
          - github.com/ethereum/go-ethereum/core/types
          - github.com/0xPellNetwork/pell-middleware-contracts
          - github.com/ethereum/go-ethereum/log
          - github.com/prometheus/client_golang/prometheus
          - github.com/AlecAivazis/survey/v2
          - github.com/ethereum/go-ethereum/rlp
          - github.com/prometheus/client_model/go
          - github.com/prometheus/common/expfmt
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/rs/zerolog
          - github.com/cometbft/cometbft-db
          - github.com/0xPellNetwork/pelldvs-libs
          - github.com/0xPellNetwork/contracts
          - github.com/0xPellNetwork/pell-middleware-contracts
          - github.com/cosmos
          - github.com/cometbft
          - github.com/adlio/schema
          - github.com/btcsuite/btcd
          - github.com/fortytw2/leaktest
          - github.com/go-kit
          - github.com/google/uuid
          - github.com/gorilla/websocket
          - github.com/lib/pq
          - github.com/oasisprotocol/curve25519-voi/primitives/merlin
          - github.com/golang/protobuf/proto
          - github.com/ory/dockertest
          - github.com/pkg/errors
          - github.com/prometheus/client_golang/prometheus/promhttp
          - github.com/spf13
          - github.com/stretchr/testify
          - github.com/decred/dcrd/dcrec/secp256k1/v4
          - github.com/ethereum/go-ethereum/crypto
          - github.com/ethereum/go-ethereum/common
          - github.com/ethereum/go-ethereum/log
          - github.com/prometheus/client_golang/prometheus
          - github.com/AlecAivazis/survey/v2
          - github.com/ethereum/go-ethereum/rlp
          - github.com/ethereum/go-ethereum/accounts/abi/bind
          - github.com/prometheus/client_golang/prometheus/testutil
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - gotest.tools/v3/assert
  revive:
    enable-all-rules: true
    rules:
      - name: comment-spacings # temporarily disabled
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: deep-exit
        disabled: true
      - name: file-header
        disabled: true
      - name: function-length
        disabled: true
      - name: function-result-limit
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: add-constant
        disabled: true
      - name: empty-lines
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: modifies-value-receiver
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: defer
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: unhandled-error
        disabled: true
        arguments:
          - "fmt.Printf"
          - "fmt.Print"
          - "fmt.Println"
  gosec:
    excludes:
      - G115
